name: wildsnap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  image: ^4.7.2
  http: ^1.1.0
  provider: ^6.1.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  percent_indicator: ^4.2.5
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
